name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing server ssh
      uses: appleboy/ssh-action@master
      with:
        host: juhanaviitamo.fi
        username: jviitamo 
        key: ${{ secrets.DEPLOYMENT_SECRET }} 
        port: 22
        script: |
          cd my-website
          git pull origin main
          git status